### ISSUE TITLE
Adding progress bar while upgrading

### ISSUE THREAD

**Issue by wondie** [geonomad-consulting/stdm#10]
The process takes few seconds. It would be good to show a progress bar while the code is running.

**Comment by wondie** [comment]
The progress bar added is QGIS progress bar but throughout STDM we use PyQt progress bar. 

Edit: for consistency it is good to use PyQt Progress bar.

**Comment by geonomad-consulting** [comment]
This issue has been fixed by this [commit](https://github.com/geonomad-consulting/stdm/commit/a57e2840a5bcc376cac1eaf4fde0d30b3fc424bf)

**Comment by wondie** [comment]
This issue is not fully fixed. The suggested progress bar to be Qt progress bar not QGIS.

**Comment by geonomad-consulting** [comment]
I believe using Qgsmessagebar class is the way to go.

**Comment by wondie** [comment]
I disagree. This is not consistent with STDM.
