### ISSUE TITLE
The upgrade dialog doesn't represent the process

### ISSUE THREAD

**Issue by wondie** [geonomad-consulting/stdm#24]
The dialog shows the user "Do you want to Backup your configuration file?" This may be misleading and the user could say No. 
![image](https://cloud.githubusercontent.com/assets/9709624/17360436/3fd4ca52-5974-11e6-9325-933b4bba8c4a.png)

In stead, I suggest the following message. 

```
Do you want to upgrade your configuration to the new version? 

If you click No, your configuration and data will no longer be accessible to STDM.

If you click Yes, you will be able to access your old configuration with the data. 

                                                Yes            No
```

**Comment by geonomad-consulting** [comment]
This is fixed by this [commit](https://github.com/geonomad-consulting/stdm/commit/eda3dd1f2d7b9365be29b5f034508485eb36ae68)

**Comment by wondie** [comment]
Yes, could replace backup with Upgrade and remove file from the first line?

**Comment by geonomad-consulting** [comment]
This issue has been fixed by this [commit](https://github.com/geonomad-consulting/stdm/commit/a57e2840a5bcc376cac1eaf4fde0d30b3fc424bf)

**Comment by wondie** [comment]
This is not fully fixed, it should have been like this. 
![image](https://cloud.githubusercontent.com/assets/9709624/17390550/da3629ae-5a16-11e6-85cd-bfda32c89809.png)

What it says currently is still
Do you want to 

> Do you want to backup your configuration file?

**Comment by geonomad-consulting** [comment]
I prefer "Do you want to upgrade our configuration file"

**Comment by wondie** [comment]
Adding file doesn't give a full picture. They are also migrating their database tables from the old to the new one. So it is not just upgrading the files but also upgrading the database tables.

**Comment by geonomad-consulting** [comment]
The I will use "Do you want to upgrade our configuration file and import your data?"

**Comment by wondie** [comment]
That is cool.

**Comment by geonomad-consulting** [comment]
This issue is fixed by this [commit](https://github.com/geonomad-consulting/stdm/commit/40fb3f7ccfd7c5434df627edbcddbcbf08531e68)
