### ISSUE TITLE
Data couldn't be imported in almost all tables 

### ISSUE THREAD

**Issue by wondie** [geonomad-consulting/stdm#37]
Data couldn't be imported in almost all tables. The only table with data is the ba_spatial_unit table.

**Comment by geonomad-consulting** [comment]
This issue is fixed.

**Comment by wondie** [comment]
It is not fixed yet. I just tested it now. Did it work on your side with the new Zambia data?

**Comment by geonomad-consulting** [comment]
Does the new Zambia data use same stdmconfig.xml or it's a different one? Since the new Zambia data has some columns that are not there in the old configuration file.

**Comment by wondie** [comment]
I have just emailed an updated configuration.

**Comment by geonomad-consulting** [comment]
I have tested the Kenya data and it seems the data is corrupt. If you look in the rows, there are mixture of both Male/Female and foreign key representation 1/2.   

![image](https://cloud.githubusercontent.com/assets/17067856/17880797/0da82d6e-6908-11e6-9691-d0618b01be3e.png)

**Comment by wondie** [comment]
That is a problem but it can be fixed I guess. You can test the Zambia one.

**Comment by geonomad-consulting** [comment]
There are problems that made old configuration not to work and the configuration updater can't correct them. About the Zambia configuration, it's still missing some columns that are there in the database like party table has a column signature which is missing in the configuration.

**Comment by geonomad-consulting** [comment]
Disregard the above comment, just refreshed my email and saw the new configuration.

**Comment by wondie** [comment]
Ok noted.

**Comment by geonomad-consulting** [comment]
This issue has been fixed with [commit](https://github.com/geonomad-consulting/stdm/commit/01dc0792071ac6f183c1e0f200c74764c6f28fc4)

**Comment by wondie** [comment]
This issue is now fixed.
